# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

protobuf_library(
    # `name` defaults to the name of this directory, i.e., `protos`.
    # `sources` defaults to ["*.proto"].
    dependencies=[
        "//:protobuf",
    ],
)
