# Copyright 2020 Pants project contributors.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# `name` defaults to the name of this directory, i.e., `proto`.
# `sources` defaults to ["*.proto"].
protobuf_library()
